### DISCUSSION TITLE
能否提供配置文件的格式

### DISCUSSION THREAD

**Discussion by ayanami-desu** [jeessy2/ddns-go#898] [General]
通过网页配置不太方便

**Comment by jeessy2** [comment]
可以用网页保存一次，即可生成配置文件。
主打网页配置，手动配置不推荐

**Reply by ayanami-desu** [reply]
不要光为小白考虑啊

**Reply by jeessy2** [reply]
推荐你看代码手写配置😓

**Comment by JingBh** [comment]
+1，希望文档中添加配置文件的格式

比如在服务器上使用的时候，要想使用 web ui 还要配置防火墙或者反向代理，比较麻烦，这种情况下我更倾向于手写配置。所以希望可以在文档中说明配置文件的格式，这样可以免去看代码来推断配置格式。

**Comment by jeessy2** [comment]
```yaml
dnsconf:
    - ipv4:
        enable: true
        gettype: url
        url: https://myip4.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net, https://4.ipw.cn
        netinterface: ""
        cmd: ""
        domains:
            - example.com
      ipv6:
        enable: true
        gettype: url
        url: https://speed.neu6.edu.cn/getIP.php, https://v6.ident.me, https://6.ipw.cn
        netinterface: ""
        cmd: ""
        ipv6reg: ""
        domains:
            - example.com
      dns:
        name: cloudflare
        id: ""
        secret: ""
      ttl: ""
user:
    username: ""
    password: ""
webhook:
    webhookurl: ""
    webhookrequestbody: ""
    webhookheaders: ""
notallowwanaccess: true
lang: zh
```
