### DISCUSSION TITLE
docker host下使用docker compose部署時如何配置監聽端口?

### DISCUSSION THREAD

**Discussion by Nebulosa-Cat** [jeessy2/ddns-go#982] [Q&A] [answered]
目前配置
```yaml
  ddns-go:
    image: jeessy/ddns-go:latest
    network_mode: host
    restart: always
    volumes:
      - ./opt/ddns-go:/root
```
不確定怎樣把-l :xxxx 寫在配置檔案內
