### ISSUE TITLE
docker 部署能增加个环境变量自定义web端口吗？

### ISSUE THREAD

**Issue by occoc** [jeessy2/ddns-go#1470]
### Description

使用了host网络，想要改成其他高位端口，看了dockerfile是固定写死的9876，可以增加一下环境变量设置吗？

### Checklist

- [x] I am using the latest version and have confirmed that the feature is not yet implemented in the latest version
- [x] I have searched for similar feature requests before submitting this one

**Comment by occoc** [comment]
```yaml
services:
  ddns-go:
    image: jeessy/ddns-go
    container_name: ddns-go
    network_mode: host
    restart: always
    volumes:
      - ./data:/root
    command: ["-l", ":64474", "-f", "300"]
```
已通过command解决
