### ISSUE TITLE
[Bug]：5.0.0 版本多个Domains解析失败

### ISSUE THREAD

**Issue by VergilGao** [jeessy2/ddns-go#624]
### 问题描述

昨天更新到5.0.0 版本后，多Domains解析失效，一直在报错

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

v5.0.0

### 安装方式

Docker

### 额外信息

![image](https://user-images.githubusercontent.com/8655163/224602418-699e3be1-7ac2-44ad-a038-832cc19c510b.png)
![image](https://user-images.githubusercontent.com/8655163/224602508-c7497e42-b5c8-447e-9a8c-6cc61314bc26.png)
![image](https://user-images.githubusercontent.com/8655163/224602550-f3f614ff-d444-40a7-9aed-4e7b3d53af26.png)

**Comment by jeessy2** [comment]
看下域名怎么填写的。重要的用xxx代替

**Comment by VergilGao** [comment]
```
a.example.com
b.example.com
```

**Comment by jeessy2** [comment]
把配置文件发来看下。重要信息用xx替代

**Comment by VergilGao** [comment]
```
dnsconf:
    - ipv4:
        enable: true
        gettype: url
        url: https://myip4.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net, https://4.ipw.cn
        netinterface: ""
        cmd: ""
        domains:
            - |-
              a.example.com
              b.example.com
              c.example.com
      ipv6:
        enable: false
        gettype: url
        url: https://speed.neu6.edu.cn/getIP.php, https://v6.ident.me, https://6.ipw.cn
        netinterface: ""
        cmd: ""
        ipv6reg: ""
        domains:
            - ""
      dns:
        name: dnspod
        id: "123456"
        secret: aaaaaaaaaaaaaaaaaaaa
      ttl: ""
user:
    username: user
    password: passwd
webhook:
    webhookurl: ""
    webhookrequestbody: ""
notallowwanaccess: true
```
