### ISSUE TITLE
[Bug]：docker 配置代理报错

### ISSUE THREAD

**Issue by yanshouwang** [jeessy2/ddns-go#665]
### 问题描述

配置 Google Domains 域名需要设置代理，在环境变量中设置代理后，日志报错

docker-compose.yml: 
```
...
services:
  ddns-go:
    image: jeessy/ddns-go:latest
    container_name: ddns-go
    environment:
      - HTTP_PROXY="192.168.0.2:8080"
      - HTTPS_PROXY="192.168.0.2:8080"
      - NO_PROXY="localhost,127.0.0.1,::1"
    volumes:
      - ddns-go:/root
    network_mode: host
    restart: unless-stopped
...
```

### 是否已搜索同类问题

已搜索，但未能解决

### 操作系统

Linux

### 架构

x86_64

### ddns-go 版本

v5.0.5

### 安装方式

Docker

### 额外信息

docker 日志：

ddns-go  | 2023/04/08 18:09:20 第一次运行将等待 10 秒后运行 (等待网络)
ddns-go  | 2023/04/08 18:09:20 监听 :9876 ...
ddns-go  | 2023/04/08 18:10:02 client.Do失败. Error:  Post "https://domains.google.com/nic/update?hostname=xxx&myip=xxx": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
ddns-go  | 2023/04/08 18:10:02 修改域名解析 xxx 失败！
