### ISSUE TITLE
docker配置保存问题

### ISSUE THREAD

**Issue by ptsa** [jeessy2/ddns-go#8]
建议添加环境变量，或者配置文件保存位置
docker compose

version: "2"

services:
   miniflux:
     image: jeessy/ddns-go
     container_name: ddns-go
     restart: always
     ports:
       - 9876:9876

**Comment by jeessy2** [comment]
可以加一个挂载宿主机的目录
```
docker run -d \
  --name ddns-go \
  --restart=always \
  -v /opt/ddns-go:/root/ \
  -p 9876:9876 \
  jeessy/ddns-go
```

**Comment by ptsa** [comment]
感觉 用docker compose

**Comment by jeessy2** [comment]
大部分人都没听说过docker compose。配置起来复杂了，所以搞网页中配置。你喜欢手动也可以手动修改配置文件。

**Comment by ptsa** [comment]
如果可以的话 建议环境变量功能加一下

**Comment by jeessy2** [comment]
看了代码环境变量不好加。建议使用直接修改配置文件.ddns_go_config.yaml
```
ipv4:
  enable: true
  url: https://myip.ipip.net
  domains:
  - 2.your_domain.com
ipv6:
  enable: false
  url: https://api-ipv6.ip.sb/ip
  domains:
  - ""
dns:
  name: alidns
  id: xxx
  secret: xxxxxx
```
