### ISSUE TITLE
自动回复相似 Issues

### ISSUE THREAD

**Issue by WaterLemons2k** [jeessy2/ddns-go#836]
### 功能描述

考虑使用 [actions-cool/issues-similarity-analysis](https://github.com/actions-cool/issues-similarity-analysis) 自动回复相似的 Issues。

### 解决的问题

提示用户提交了相似的 Issues。

### 附加信息

GitHub Actions 工作流参考：

```yaml
name: Issues Similarity Analysis

on:
  issues:
    types: [opened, edited]

jobs:
  similarity-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: analysis
        uses: actions-cool/issues-similarity-analysis@v1
        with:
          filter-threshold: 0.5
          comment-title: '### See'
          comment-body: '${index}. ${similarity} #${number}'
          show-footer: false
```

### 检查清单

- [X] 我已搜索同类问题，并确保没有我要提交的功能
- [X] 我已使用最新版本，并确保该功能仍未在最新版本中实现
